#!/usr/bin/env bash 

N=`basename $0`
C="$0"
C=`dirname "$C"`
C=`ls -d1 "$C"`

echo "$C"

TARGET_FILE="$C"

# cd "$(dirname "$TARGET_FILE")" 
# TARGET_FILE=$(readlink "$TARGET_FILE")
# TARGET_FILE=$(basename "$TARGET_FILE")



cd `dirname $TARGET_FILE`
TARGET_FILE=`basename $TARGET_FILE`

# Iterate down a (possible) chain of symlinks
while [ -L "$TARGET_FILE" ]
do
    TARGET_FILE=`readlink $TARGET_FILE`
    cd `dirname $TARGET_FILE`
    TARGET_FILE=`basename $TARGET_FILE`
done

# Compute the canonicalized name by finding the physical path 
# for the directory we're in and appending the target file.
PHYS_DIR=`pwd -P`
RESULT=$PHYS_DIR/$TARGET_FILE

# echo $RESULT

C="$RESULT"

# echo "$C"


# "$*"
# TSINGULAR="$C/../bin/Singular"
SINGULAR="$C/../bin/$N"
# EMACS=`which emacs`

# echo "$S"
## echo "$A"
A="-v"

# A="--singular=$SINGULAR -v" 
# index??!
# export SINGULAR_INFO_FILE="$C/..."

osascript -e "tell app \"Terminal\" 
do script \"$SINGULAR $A; exit \" 
end tell"
    
# exec $TSINGULAR $A